# Generated by Django 2.0.5 on 2018-06-22 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(choices=[('C', 'c'), ('JAVA', 'java')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('question', models.CharField(max_length=120)),
                ('answer', models.CharField(max_length=120)),
                ('language_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Language')),
            ],
        ),
    ]
