# Generated by Django 2.0.5 on 2018-06-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20180622_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='language_used',
        ),
        migrations.AddField(
            model_name='question',
            name='c_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='java_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
